name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (ruff + black)
        continue-on-error: true
        run: |
          ruff check code tests
          black --check code tests
      - name: Pytest
        run: |
          mkdir -p reports
          pytest -q --maxfail=1 --junitxml=reports/test-results.xml
      - name: Validate schema
        run: make validate_schema
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/test-results.xml
          if-no-files-found: ignore
